---
name: CI

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Lint YAML
        run: |
          pip install yamllint
          yamllint .

      - name: Check Python formatting
        # yamllint disable-line rule:line-length rule:comments
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89  # v4.1.0
        with:
          args: "format scripts/ tests/ --check"

      - name: Check Python linting
        # yamllint disable-line rule:line-length rule:comments
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89  # v4.1.0
        with:
          args: "check scripts/ tests/"

      - name: Check shell scripts
        run: shellcheck scripts/*.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest tests/ -v
