---
name: CI

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Lint YAML
        run: |
          pip install yamllint
          yamllint .

      - name: Check Python formatting
        # yamllint disable-line rule:line-length rule:comments
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6  # v3.6.1
        with:
          args: "format scripts/ tests/ --check"

      - name: Check Python linting
        # yamllint disable-line rule:line-length rule:comments
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6  # v3.6.1
        with:
          args: "check scripts/ tests/"

      - name: Check shell scripts
        run: shellcheck scripts/*.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # yamllint disable-line rule:line-length rule:comments
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest tests/ -v
